In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6],
    [6, 7, 8],
    [9, 10, 11]
])
y = np.array([1, 2, 3, 4, 5])

In [ ]:
train_test_split(x, y, train_size=0.8, random_state=42)

[array([[ 9, 10, 11],
        [ 4,  5,  6],
        [ 1,  2,  3],
        [ 6,  7,  8]]),
 array([[2, 3, 4]]),
 array([5, 3, 1, 4]),
 array([2])]

In [16]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.8, random_state=42)

In [21]:
xtrain

array([[ 9, 10, 11],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 6,  7,  8]])

In [22]:
xtest

array([[2, 3, 4]])

In [23]:
ytrain

array([5, 3, 1, 4])

In [24]:
ytest

array([2])